### ISSUE TITLE
PanTro4 reference

### ISSUE THREAD

**Issue by CLeib** [BenjaminPeter/admixfrog#4]
Hi,
How was the pseudo haploid panTro4 reference sample created for the reference file? 
Thanks,
Chen

**Comment by JielinLi** [comment]
Hi, 
Have you solved the problem? I also have the same issue.

**Comment by CLeib** [comment]
Hi,
I ended up using python module [MafIO](https://biopython.org/docs/1.75/api/Bio.AlignIO.MafIO.html) to get the chimp genotype for each position in my VCF from MAF files (downloaded from [UCSC](https://hgdownload.cse.ucsc.edu/goldenPath/hg19/vsPanTro5/mafSynNet/)), and then using _bcftools convert_ to turn it into a VCF. 
I'm sure there is a better way to do this, as this is quite time consuming, but it was the best I was able to come up with.

**Comment by JielinLi** [comment]
Hi,
You explained it very clearly, I understand now. Thank you so much!

**Comment by JielinLi** [comment]
Hi,
I want to ask if your file is like this:

22	17032698	T	
22	17054720	C	
22	17057138	A	
22	17075353	C

the first column is the chromosome, the second column is the position of hg19 and the third columns is the pantro5 genotype in this position.
Thank you so much!

**Comment by CLeib** [comment]
Hi,

Yes, that's it :)

If you wish to convert it into a VCF, you can now use:
`bcftools convert -c CHROM,POS,AA --tsv2vcf <mafIO_output.tsv> -f <hg19_ref.fasta> -s <sample_name> -o <output_name>`

**Comment by JielinLi** [comment]
Hi,

I made it. Thank you so much!
